### ISSUE TITLE
Can I store a Date class variable?

### ISSUE THREAD

**Issue by 15555** [diareuse/mCache#5]
I have a next class that stored in cache:
```
data class OfficeLocationDTOContainer(
    var offices: ArrayList<SomeOtherClass>? = null, 
    var updatedAt: Date)
```
storage called like this:
```
val container = OfficeLocationDTOContainer(someArray, Date())
container.give().build().getNow()
```
retrieval of data:
```
obtain<OfficeLocationDTOContainer>().build().getNow()?.let { 
    ...
}
```
Library caches all of this data successfully on my device. But i have some crash reports on several devices, where library can't parse date: 
```
Caused by java.text.ParseException
Failed to parse date ["Feb 14, 2018 20:35:04']: Invalid number: Feb (at offset 0)
```
stack trace from crash:
```
wiki.depasquale.mcache.FileConverter.decode (FileConverter.kt:59)
wiki.depasquale.mcache.FileConverter.run$mcache_release (FileConverter.kt:39)
wiki.depasquale.mcache.FilePresenter.getNow (FilePresenter.kt:27)
```
I have never caught this issue on phones that tested by me.
The question is why it behaves differently on other devices?

**Comment by diareuse** [comment]
`Date().toString()` or it's serialization within GSON is possibly implemented differently on wide range of devices.

What the library only does is taking the input, serializes it via GSON and base64s it to a file.

Since you are using kotlin I would recommend using the `Date` variable as a getter/setter only and store millis value (just like you'd get from `System.currentTimeMillis()` like so:

```kotlin
data class OfficeLocationDTOContainer(
    var offices: ArrayList<SomeOtherClass>? = null,
    var _updatedAt: Long
) {
    @Transient
    var updatedAt: Date = Date(_updatedAt)
        set(value) {
            field = value
            _updatedAt = value.time
        }
}
```

I will not do that myself since it would disrupt caches for other users, ultimately causing crashes. However I have added option to set Gson programmatically so you can define your own strategy. 😃

**Comment by 15555** [comment]
Thank you, for your quick reply. 
I had the same idea to fix this issue, but I was just confused with this strange behavior.
